"""add vector_document_id to knowledge

Revision ID: 1e78ec1e191d
Revises: 71630bb4f80c
Create Date: 2026-07-20 16:45:04.843227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e78ec1e191d'
down_revision: Union[str, Sequence[str], None] = '71630bb4f80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge', sa.Column('vector_document_id', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'knowledge', ['vector_document_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge', type_='unique')
    op.drop_column('knowledge', 'vector_document_id')
    # ### end Alembic commands ###
