"""create users table

Revision ID: dce517f3ecd8
Revises: 
Create Date: 2026-07-08 21:46:17.747023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce517f3ecd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('service_type', sa.Enum('PREPAID', 'POSTPAID', 'BROADBAND', 'DTH', 'AIRTEL_BLACK', name='servicetype'), nullable=False),
    sa.Column('customer_type', sa.Enum('REGULAR', 'PREMIUM', 'VIP', name='customertype'), nullable=False),
    sa.Column('preferred_language', sa.String(length=30), nullable=False),
    sa.Column('circle', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'AGENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_index(op.f('ix_users_customer_id'), 'users', ['customer_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_customer_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
